### ISSUE TITLE
Documentation and errors insufficeint to get vocola working.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#109]
1.  it appears vocola2 and unimacro require user to install them with pip, but how is that realistic?  Does the user have to go, manually set the path to a specific python, and run pip, just to install these?  This is too much, and more complicated than we had last fall (i.e. pip install natlink unimacro and run natlinkconfig).

I managed to get them installed with pip,   into C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\unimacro 
and
C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro

My natlink config looks like 
`[directories]
unimacrogrammarsdirectory = C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\unimacro
vocolagrammarsdirectory = C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\vocola
vocoladirectory = C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2
unimacrodirectory = C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro

[userenglish-directories]

[userspanish-directories]

[settings]
log_level = DEBUG
load_on_startup = True
load_on_begin_utterance = False
load_on_mic_on = True
load_on_user_changed = True

`

I get errors that look like this, no idea how to resolve.

`Natlink Version: 5.1.3
Python Version: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:39:15) [MSC v.1929 32 bit (Intel)]
Natlink is loaded...

set log level to: DEBUG
starting natlink loader from config file:
	"C:\Users\Doug\.natlink\natlink.ini"
get_user_language, return userLanguage: "enx", (long language: "Canadian English")
set_user_language, user: "doug ransom office", profile: "C:\Users\Doug\AppData\Local\Nuance\NS15\Users\doug ransom office\current", language: "enx"
triggering load/reload process
loading module: __init__
loading module: _vocola_main
DPI awareness could not be set; it has been set already.
created directory: {directory}
---copy AutoHotkey script "getintoforeground.ahk" from
Samples directory to "C:\Users\Doug\.autohotkey"----
---copy AutoHotkey script "showmessageswindow.ahk" from
Samples directory to "C:\Users\Doug\.autohotkey"----
unimacroactions, inifile: C:\Users\Doug\.dtactions\unimacro\unimacroactions.ini
VocolaEnabled: False
Traceback (most recent call last):
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 301, in load_or_reload_module
    module = self._import_module_from_path(mod_path)
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 257, in _import_module_from_path
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2\_vocola_main.py", line 91, in <module>
    raise OSError(f'Vocola is not Enabled, but this directory "{thisDir}" seems to be in the "directories" section of Natlink, please check your configuration.')
OSError: Vocola is not Enabled, but this directory "C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2" seems to be in the "directories" section of Natlink, please check your configuration.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 301, in load_or_reload_module
    module = self._import_module_from_path(mod_path)
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 257, in _import_module_from_path
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2\_vocola_main.py", line 91, in <module>
    raise OSError(f'Vocola is not Enabled, but this directory "{thisDir}" seems to be in the "directories" section of Natlink, please check your configuration.')
OSError: Vocola is not Enabled, but this directory "C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2" seems to be in the "directories" section of Natlink, please check your configuration.
load_or_reload_module, exception, add to self.bad_modules C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2\_vocola_main.py
loading module: __init__
loading module: _control

No Unimacro sample directory not found: %s
CHECK YOUR CONFIGURATION!!!!!!!!!!!!!!!!

cannot make inifiles directory: 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 301, in load_or_reload_module
    module = self._import_module_from_path(mod_path)
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 257, in _import_module_from_path
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro\_control.py", line 27, in <module>
    from unimacro import natlinkutilsbj as natbj
  File "C:\Users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro\natlinkutilsbj.py", line 182, in <module>
    os.mkdir(tmpDirectory)
PermissionError: [WinError 5] Access is denied: 'tmp'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 301, in load_or_reload_module
    module = self._import_module_from_path(mod_path)
  File "C:\Program Files (x86)\Natlink\site-packages\natlink\loader.py", line 257, in _import_module_from_path
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro\_control.py", line 27, in <module>
    from unimacro import natlinkutilsbj as natbj
  File "C:\Users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro\natlinkutilsbj.py", line 182, in <module>
    os.mkdir(tmpDirectory)
PermissionError: [WinError 5] Access is denied: 'tmp'
load_or_reload_module, exception, add to self.bad_modules C:\users\Doug\AppData\Roaming\Python\Python39\site-packages\unimacro\_control.py
`
What can i do with that information?

**Comment by dougransom** [comment]
here is a workaround not you have to be in the correct python folder so you get the python39-32 python.exe

`C:\Program Files (x86)\Python39-32> .\python 'C:\Program Files (x86)\Natlink\NatlinkConfigure\natlinkconfigfunctions.py'`

**Comment by quintijn** [comment]
Better follow you other plan first, to call natlinkconfigfunctions.py via a script.

I agree that configuring unimacro and vocola manually is a pain. The vocolagrammardirectory and the unimacrogrammardirectory should NOT be in a shared folder.

And Unimacro and Vocola also need their own sections [unimacro] and [vocola] with the vocolauserdirectory and the unimacrouserdirectory specified (which may be shared).

BTW. LexiconCode is working on a GUI config program, based upon these natlinkconfigfunctions.py. 

So hopefully we get things working better soon by now.
