### ISSUE TITLE
natlinkconfig_cli.exe and natlinkconfig_gui.exe

### ISSUE THREAD

**Issue by Voxellence** [dictation-toolbox/natlink#140]
I've installed the latest pre-release of NatLink.

When I run natlinkconfig_cli.exe I get the following:
```
Traceback (most recent call last):
  File "C:\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310-32\Scripts\natlinkconfig_cli.exe\__main__.py", line 4, in <module>
  File "C:\Python\Python310-32\lib\site-packages\natlinkcore\configure\natlinkconfig_cli.py", line 8, in <module>
    from natlinkcore.configure import natlinkconfigfunctions
  File "C:\Python\Python310-32\lib\site-packages\natlinkcore\configure\natlinkconfigfunctions.py", line 31, in <module>
    from natlinkcore import tkinter_dialogs
  File "C:\Python\Python310-32\lib\site-packages\natlinkcore\tkinter_dialogs.py", line 18, in <module>
    from tkinter import filedialog
ModuleNotFoundError: No module named 'tkinter'
```
When I run natlinkconfig_gui.exe, nothing happens.

**Comment by LexiconCode** [comment]
tkinter is a standard python library. How was the python environment installed?

**Comment by Voxellence** [comment]
I uninstalled all versions of Python on my computer, even the ones installed by Visual Studio. I purged the registry of the three relevant nodes. Then I installed the [32-bit Python 3.10.7](https://www.python.org/ftp/python/3.10.7/python-3.10.7.exe) executable located where this hyperlink points to.  

I installed NatLink Core and NatLink in the order and from the sources you pointed me to.  

Thanks.

**Comment by LexiconCode** [comment]
Uninstall Python and try again using the natlink installer? Make sure to delete the python site packages directory

This time don't worry about installing natlink core. That's handled by the installer.
