### ISSUE TITLE
Error with python3-32 on master when running start_configurenatlink.py

### ISSUE THREAD

**Issue by lexxish** [dictation-toolbox/natlink#2]
File "C:\code\natlink\MacroSystem\core\utilsqh.py", line 124

```
Traceback (most recent call last):
  File "C:\code\natlink\confignatlinkvocolaunimacro\start_configurenatlink.py", line 61, in <module>
    import natlinkconfigfunctions
  File "C:\code\natlink\confignatlinkvocolaunimacro\natlinkconfigfunctions.py", line 187, in <module>
    import natlinkstatus, natlinkcorefunctions, RegistryDict
  File "C:\code\natlink\MacroSystem\core\natlinkstatus.py", line 191, in <module>
    import natlinkcorefunctions
  File "C:\code\natlink\MacroSystem\core\natlinkcorefunctions.py", line 38, in <module>
    from inivars import IniVars
  File "C:\code\natlink\MacroSystem\core\inivars.py", line 11, in <module>
    import utilsqh
  File "C:\code\natlink\MacroSystem\core\utilsqh.py", line 124
SyntaxError: Non-ASCII character '\xc3' in file C:\code\natlink\MacroSystem\core\utilsqh.py on line 125, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Also if I try enabling unicode support in utilsqh.py then I get:

```
Traceback (most recent call last):
  File "C:\code\natlink\confignatlinkvocolaunimacro\start_configurenatlink.py", line 61, in <module>
    import natlinkconfigfunctions
  File "C:\code\natlink\confignatlinkvocolaunimacro\natlinkconfigfunctions.py", line 187, in <module>
    import natlinkstatus, natlinkcorefunctions, RegistryDict
  File "C:\code\natlink\MacroSystem\core\natlinkstatus.py", line 273, in <module>
    class NatlinkStatus:
  File "C:\code\natlink\MacroSystem\core\natlinkstatus.py", line 301, in NatlinkStatus
    userregnl = natlinkcorefunctions.NatlinkstatusInifileSection()
  File "C:\code\natlink\MacroSystem\core\natlinkcorefunctions.py", line 531, in __init__
    InifileSection.__init__(self, section=defaultSection, filename=filename)
  File "C:\code\natlink\MacroSystem\core\natlinkcorefunctions.py", line 442, in __init__
    self.ini = IniVars(filename) # want strings to be returned
  File "C:\code\natlink\MacroSystem\core\inivars.py", line 613, in __init__
    readFunc(file)
  File "C:\code\natlink\MacroSystem\core\inivars.py", line 807, in _readIni
    if sectionName in self:
  File "C:\code\natlink\MacroSystem\core\inivars.py", line 629, in __contains__
    raise TypeError('inivars, __contains__ of IniVars expects str for key "%s", not: %s'% (key, type(key)))
TypeError: inivars, __contains__ of IniVars expects str for key "usersettings", not: <type 'unicode'>
```

**Comment by lexxish** [comment]
I had to change two things to fix this:

1. I had python in my path twice so it was pointing to python2.7
2. I had to upgrade from python 3.7 to 3.8 or I had a different error on startup

**Comment by Kn0rk** [comment]
The python 3 is still work in progress and unfortunately we have not (and might not be able to) create a stable ABI for python 3.X. Currently I am compiling to python 3.7 and @mrob95 is compiling to 3.8.

The goal is that it will work seem less with both versions eventually. Thanks for posting the work around.

**Comment by quintijn** [comment]
utilsqh.py is fixed.

How we can force a start with python3 is not clear to me... With a shebang line at the top maybe?

**Comment by quintijn** [comment]
shebang line added, so problem solved

**Comment by lexxish** [comment]
> The python 3 is still work in progress and unfortunately we have not (and might not be able to) create a stable ABI for python 3.X. Currently I am compiling to python 3.7 and @mrob95 is compiling to 3.8.
> 
> The goal is that it will work seem less with both versions eventually. Thanks for posting the work around.

I wanted to try python 3.6 because [psychopy ](https://www.psychopy.org/api/iohub/device/eyetracker_interface/Tobii_Implementation_Notes.html) seems to work only with 3.6 but getting the below error. Any thoughts on why? 

```
Traceback (most recent call last):
  File "configurenatlink.pyw", line 1363, in <module>
    app = MyApp(True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\wx\core.py", line 2194, in __init__
    self._BootstrapApp()
SystemExit: OnInit returned false, exiting...

```
