### ISSUE TITLE
Logging Problem

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#203]
Quintijn Hoogenboom, [2024-07-31 8:57 AM]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files (x86)\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python310-32\Scripts\natlinkconfig_gui.exe\__main__.py", line 4, in <module>
    from natlinkcore.configure.natlinkconfig_gui import main_gui
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 215, in <module>
    func_to_call(values, event)
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 133, in UnimacroUserDir
    Config.disable_unimacro()
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 368, in disable_unimacro
    self.clearDirectory('UnimacroUserDirectory', section='unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 257, in clearDirectory
    logging.info(f'cleared "{option}"')
Message: 'cleared "UnimacroUserDirectory"'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python310-32\site-packages\FreeSimpleGUI\FreeSimpleGUI.py", line 13645, in _long_func_thread
    return_value = original_func()
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 131, in <lambda>
    window.perform_long_operation(lambda: Config.enable_unimacro(values['Set_UserDir_Unimacro']), 'Thread_Done_Unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 349, in enable_unimacro
    do_pip("install", "unimacro")
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 48, in do_pip
    logging.info(f"command:  {command} ")
Message: "command:  ['C:\\\\Program Files (x86)\\\\Python310-32\\\\pythonw.exe', '-m', 'pip', 'install', 'unimacro'] "
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python310-32\site-packages\FreeSimpleGUI\FreeSimpleGUI.py", line 13645, in _long_func_thread
    return_value = original_func()
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 131, in <lambda>

Quintijn Hoogenboom, [2024-07-31 8:57 AM]
window.perform_long_operation(lambda: Config.enable_unimacro(values['Set_UserDir_Unimacro']), 'Thread_Done_Unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 349, in enable_unimacro
    do_pip("install", "unimacro")
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 50, in do_pip
    logging.debug(f"completed_process:  {completed_process}")
Message: "completed_process:  CompletedProcess(args=['C:\\\\Program Files (x86)\\\\Python310-32\\\\pythonw.exe', '-m', 'pip', 'install', 'unimacro'], returncode=0, stdout=b'Defaulting to user installation because normal site-packages is not writeable\\r\\nCollecting unimacro\\r\\n  Using cached unimacro-4.1.5-py3-none-any.whl.metadata (3.0 kB)\\r\\nRequirement already satisfied: dtactions>=1.5.7 in c:\\\\program files (x86)\\\\natlink\\\\site-packages (from unimacro) (1.6.1)\\r\\nRequirement already satisfied: debugpy>=1.2.0 in c:\\\\program files (x86)\\\\natlink\\\\site-packages (from unimacro) (1.8.2)\\r\\nRequirement already satisfied: pywin32>=304 in c:\\\\program files (x86)\\\\natlink\\\\site-packages (from unimacro) (306)\\r\\nRequirement already satisfied: natlinkcore>=5.3.7 in c:\\\\program files (x86)\\\\python310-32\\\\lib\\\\site-packages (from unimacro) (5.3.13)\\r\\nRequirement already satisfied: pysimplegui in c:\\\\program files (x86)\\\\python310-32\\\\lib\\\\site-packages (from unimacro) (5.0.5)\\r\\nRequirement already satisfied: platformdirs in c:\\\\program files (x86)\\\\natlink\\\\site-packages (from dtactions>=1.5.7->unimacro) (4.2.2)\\r\\nRequirement already satisfied: FreeSimpleGUI>=5.1.0 in c:\\\\users\\\\gebruiker\\\\appdata\\\\roaming\\\\python\\\\python310-32\\\\site-packages (from natlinkcore>=5.3.7->unimacro) (5.1.0)\\r\\nRequirement already satisfied: pydebugstring>=1.0.0.1 in c:\\\\program files (x86)\\\\python310-32\\\\lib\\\\site-packages (from natlinkcore>=5.3.7->unimacro) (1.0.0.2)\\r\\nRequirement already satisfied: rsa in c:\\\\program files (x86)\\\\python310-32\\\\lib\\\\site-packages (from pysimplegui->unimacro) (4.9)\\r\\nRequirement already satisfied: pyasn1>=0.1.3 in c:\\\\program files (x86)\\\\python310-32\\\\lib\\\\site-packages (from rsa->pysimplegui->unimacro) (0.6.0)\\r\\nUsing cached unimacro-4.1.5-py3-none-any.whl (497 kB)\\r\\nInstalling collected packages: unimacro\\r\\nSuccessfully installed unimacro-4.1.5\\r\\n', stderr=b'\\r\\n[notice] A new release of pip is available: 24.1.2 -> 24.2\\r\\n[notice] To update, run: C:\\\\Program Files (x86)\\\\Python310-32\\\\pythonw.exe -m pip install --upgrade pip\\r\\n')"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python310-32\site-packages\FreeSimpleGUI\FreeSimpleGUI.py", line 13645, in _long_func_thread
    return_value = original_func()
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 131, in <lambda>
    window.perform_long_operation(lambda: Config.enable_unimacro(values['Set_UserDir_Unimacro']), 'Thread_Done_Unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 356, in enable_unimacro
    self.setDirectory('UnimacroUserDirectory', arg, section='unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 240, in setDirectory
    logging.info(f'Set in section "{section}", option "{option}" to "{dir_path}"')

Quintijn Hoogenboom, [2024-07-31 8:57 AM]
Message: 'Set in section "unimacro", option "UnimacroUserDirectory" to "C:/Users/Gebruiker/Documents/unimacro_qh"'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python310-32\site-packages\FreeSimpleGUI\FreeSimpleGUI.py", line 13645, in _long_func_thread
    return_value = original_func()
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 131, in <lambda>
    window.perform_long_operation(lambda: Config.enable_unimacro(values['Set_UserDir_Unimacro']), 'Thread_Done_Unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 361, in enable_unimacro
    self.setDirectory('unimacrodirectory','unimacro')  #always unimacro
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 238, in setDirectory
    logging.info(f'Set option "{option}" to "{dir_path}"')
Message: 'Set option "unimacrodirectory" to "unimacro"'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python310-32\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python310-32\site-packages\FreeSimpleGUI\FreeSimpleGUI.py", line 13645, in _long_func_thread
    return_value = original_func()
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfig_gui.py", line 131, in <lambda>
    window.perform_long_operation(lambda: Config.enable_unimacro(values['Set_UserDir_Unimacro']), 'Thread_Done_Unimacro')
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 363, in enable_unimacro
    self.setDirectory('unimacrogrammarsdirectory', uniGrammarsDir)
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\configure\natlinkconfigfunctions.py", line 238, in setDirectory
    logging.info(f'Set option "{option}" to "{dir_path}"')
Message: 'Set option "unimacrogrammarsdirectory" to "unimacro\\unimacrogrammars"'
Arguments: ()

**Comment by LexiconCode** [comment]
Thank you for looking into this!
