### ISSUE TITLE
still elevation problems with pipping packages...

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlink#207]
I think, we need to do all pip installs elevated, or none (after natlink itself).

part of messages window just now:

`Natlink Version: 5.5.7
Natlink pyd path: C:\Program Files (x86)\Natlink\site-packages\natlink\_natlink_core.pyd
Python Version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)]
Natlink is loaded...

Starting natlink loader from config file:
	"C:\Users\Gebruiker\.natlink\natlink.ini"
loading module: _sample1
loading module: __init__
loading module: _vocola_main
VocolaEnabled: True
Traceback (most recent call last):
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\loader.py", line 332, in load_or_reload_module
    module = self._import_module_from_path(mod_path)
(...)
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\vocola2\_vocola_main.py", line 96, in <module>
    os.mkdir(VocolaGrammarsDirectory)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
Traceback (most recent call last):
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\loader.py", line 332, in load_or_reload_module
    module = self._import_module_from_path(mod_path)
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\loader.py", line 287, in _import_module_from_path
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\vocola2\_vocola_main.py", line 96, in <module>
    os.mkdir(VocolaGrammarsDirectory)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
`

Unimacro is locally pipped, so focus this issue on Vocola.

I have Python 3.10.11 (32 bit) installed on `C:\Program Files (x86)\Python310-32\Lib\site-packages`, with vocola2 installed there.
Also `C:\Program Files (x86)\Natlink\site-packages` with natlink and other things (no vocola2 or unimacro).

Then, from an unelevated configure session:  C:\Users\Gebruiker\AppData\Roaming\Python\Python310-32\site-packages a bunch of modules, but NOT unimacro or vocola2.

Before I had vocola2 just running on this computer...

So I am confused. 

I put it here for not forgetting about it, will try a few more things first. Quintijn

**Comment by quintijn** [comment]
![site-packages Python321-32](https://github.com/user-attachments/assets/bd35b921-3e30-4da0-982c-849878477efd)
![site-packages appdata roaming etc](https://github.com/user-attachments/assets/b70d5a8a-86eb-49a2-9ca4-ce0e63b4a870)
![site-packages Natlink](https://github.com/user-attachments/assets/2665bd04-d060-4e09-91ba-e5314f997ba9)


the 3 places where site-packages are. Probably 2 of them elevated.

**Comment by drmfinlay** [comment]
Goodness!  This is confusing me, too.  It was a lot simpler when everything was under C:\Natlink.

**Comment by LexiconCode** [comment]
And this goes back to a previously documented issue when Pip is invoked as a standard user versus elevated privileges. pip should never be executed as administrator.

Installer runs as administrator and it has to, for in-process. I'm not sure how to downgrade pip install when the installer executes pip.

Additionally PIP randomly decides sometimes to include dependencies in various places. 


This is really what started my journey working towards virtual installs.

**Comment by dougransom** [comment]
Install for all users:  
- natlink installed for all users.
- must install python for all users

Install for current user (note this can't be done for more than one user):
- natlink installed for current user
- install Python for current user.

**Comment by dougransom** [comment]
some experiements on registering natlink per user

I was able to register _natlink_core.pyd for a per user basis, and it was able to create a natlink object using a test program. Unfortunately, natlink crashes in this situation.

I will have to wait till I have a little more time and energy to put into this before I investigate further.

All i did was register with this after replacing %MODULE% by editing the file.
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\CLSID\{dd990001-bb89-11d2-b031-0060088dc929}]
@="Python Subsystem for NatSpeak"
"InprocServer32"="%MODULE%"
{
    "ThreadingModel"="Apartment"
    "AppID"="{dd990001-bb89-11d2-b031-0060088dc929}"
}

[HKEY_CURRENT_USER\Software\Classes\AppID\{dd990001-bb89-11d2-b031-0060088dc929}]
@="Python Subsystem for NatSpeak"
"DllSurrogate"=""
'''
