### ISSUE TITLE
Cannot attach python debugger

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/natlink#23]
It is super hard to make progress on unimacro and vocola without being able to attache a python debugger.  I tried pydebug and visual studio code.

This python code didn't  work when called (i embedded in a unimacro grammar), attempting to to the port with visual studio code.
`    debugpy.listen(port) `

here is the launch.json
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}"
        },
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 9000
        }
]
}`

I also tried with the above remote attach the following command line, `python -m debugpy  --listen 9000 --pid 14176 --wait-for-client --logo-to debugpy.log`  where 14176 was natspeak.exe process id at the time.

Mostly i just get an error like "connect ECONNREFUSED 127.0.0.1:9000" in visual studio.

I also tried the  "Python: Attach using Process Id" method.   That also didnt' work.  i tried all the above with firewall and defender antivirus disabled.

There should be a simple way to attach a python debugger, whether it is pydebug, or some instructions on how to run python separately from natspeak.exe if that is even possible.

**Comment by dougransom** [comment]
details for `   print(f"debugpy listen on port {port}")
    debugpy.listen(port) 
  `
We get a traceback like 

`debugpy listen on port 8322
Traceback (most recent call last):
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 218, in listen
    sock, _ = endpoints_listener.accept()
  File "C:\Python38-32\Lib\socket.py", line 292, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\natlinkutilsbj.py", line 1225, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\natlinkutilsbj.py", line 672, in resultsCallback
    self.__inherited.resultsCallback(self, wordsAndNums, resObj)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 856, in resultsCallback
    self.callRuleResultsFunctions(seqsAndRules, fullResults)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 881, in callRuleResultsFunctions
    self.callIfExists( 'gotResults_'+ruleName, (ruleWords, fullResults) )
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\natlink\MacroSystem\core\natlinkutils.py", line 379, in callIfExists
    return func(*argList)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\_control.py", line 313, in gotResults_trace
    actions.debugActions(traceNum)
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\actions.py", line 850, in debugActions
    connect_debugger()
  File "C:\Users\dougr\OneDrive\doug\dication_toolbox\Unimacro\actions.py", line 823, in connect_debugger
    debugpy.listen(port) 
  File "C:\Python38-32\lib\site-packages\debugpy\__init__.py", line 113, in listen
    return api.listen(address)
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "C:\Python38-32\lib\site-packages\debugpy\server\api.py", line 232, in listen
    raise RuntimeError("timed out waiting for adapter to connect")
RuntimeError: timed out waiting for adapter to connect
`

**Comment by reckoner** [comment]
I think you will have better luck with the wingware (wingdbstub). It is generally more reliable. You just have to make sure to set up the debugger and the breakpoints before you launch natspeak.

**Comment by dougransom** [comment]
yet  another debugger to try.  

I have reported the failure of pydebug  on github (more elaborating one on another report).   https://github.com/microsoft/debugpy/issues/456

**Comment by dougransom** [comment]
I have figured this out and am working on the minor tweaks to natlink to make this easy for anyone to set up.

**Comment by dougransom** [comment]
I have a pull request with a solution.  You can set some environment variables before starting natlink to enable debugging with  a DAP compatible debugger.  There is also a unimacro grammar available to start the DAP compatible debugging on demands.

**Comment by dougransom** [comment]
pull request i think has been taken care of.
