### ISSUE TITLE
Remove `flit install --symlink` from readme

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/natlink#64]
We need an alt for `flit install --symlink` for now use `flit install`

```
PS C:\Windows\system32> natlinkconfig_cli
Traceback (most recent call last):
  File "c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 284, in __init__
    self.__class__.NatlinkDirectory
AttributeError: type object 'NatlinkConfig' has no attribute 'NatlinkDirectory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python38-32\Scripts\\natlinkconfig_cli", line 8, in <module>
    sys.exit(main())
  File "c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 2029, in main
    cli = CLI()
  File "c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 1345, in __init__
    self.config = NatlinkConfig()
  File "c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore\ConfigureNatlink\natlinkconfigfunctions.py", line 185, in __init__
    natlinkstatus.NatlinkStatus.__init__(self, skipSpecialWarning=1)
  File "c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 289, in __init__
    self.__class__.NatlinkDirectory = self.getNatlinkDirectory(coreDir=coreDir)
  File "c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore\natlinkstatus.py", line 1356, in getNatlinkDirectory
    raise OSError(f'site-packages is symlink! {coreDir}, resolved: {cdResolved}, return {coreDir}\ndo not use --symlink with flit install')
OSError: site-packages is symlink! c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore, resolved: C:\Users\MainLaptop\Documents\natlink\src\natlinkcore, return c:\users\mainlaptop\appdata\local\programs\python\python38-32\lib\site-packages\natlinkcore
```

**Comment by LexiconCode** [comment]
this is been resolved!
