### ISSUE TITLE
Grammar lists do not work correctly with Dragon 15 in some cases

### ISSUE THREAD

**Issue by drmfinlay** [dictation-toolbox/natlink#82]
Natlink's named/dynamic grammar list functionality does not work correctly with Dragon 15 if used in a stand-alone Python process.  However, it works just fine in a command module loaded by natspeak.exe.  The related methods are `GramObj.appendList()` and `GramObj.emptyList()`.

The problem can be replicated by running my [*sample_list.py*](https://gist.github.com/Danesprite/f2110f897150ad42fa1c1f38f620e70d) Natlink command module.  The module will load without issue, but Dragon will fail to match a spoken or mimicked command to the grammar.  If one says, for example, "this big red object is good," Dragon will normally output the spoken words instead.  It would seem that Dragon is either not receiving or not setting the list words and therefore cannot recognize the command.  If the module is loaded into natlink normally via the user directory, it will work properly.

This behaviour occurs in the older Python 2.7 and the newer Python 3.8 versions of Natlink.

I note that this can only be related to the C++ code since Dragonfly, which uses the `GramObj` class directly, has the same problem.

This issue, if it is indeed fixable and not another Dragon "quirk" we must simply endure, should be considered low priority since Natlink is not normally used in this fashion.

**Comment by DanKaplanSES** [comment]
This would add convenience for me, because it would allow me to have a dragonfly grammar that consistently capitalizes words.

**Comment by Danesprite** [comment]
This issue with lists is unrelated to the problem we have been discussing
on the Caster Gitter channel.

I suspect that problem is a regression in Dragonfly that has, until now,
gone virtually unnoticed, since most users make use of grammar, rather than
grammar rule, contexts.  Either that, or it is a quirk of DNS itself.  I
see nothing unusual in the relevant parts of the Natlink source code.

**Comment by LexiconCode** [comment]
DNS 13 is the expected outcome for in process?
```
Heard macro "sample list"
Heard macro "sample list"
```
Updated the imports from @Danesprite example.
```py
import natlink
from natlinkcore.natlinkutils import GrammarBase

class ThisGrammar(GrammarBase):

    gramSpec = """
        <start> exported = this <ruleOne> is {list};
        <ruleOne> = big <ruleTwo> object;
        <ruleTwo> = red | blue;
    """
    
    def initialize(self):
        self.load(self.gramSpec)
        self.activateAll()

        # Add a dynamic list containing the words "good" and "bad".
        self.setList("list", ["good", "bad"])

    def gotResults_start(self,words,fullResults):
        natlink.playString('Heard macro "sample list"{enter}')

if __name__ == '__main__':
    natlink.natConnect()

thisGrammar = ThisGrammar()
thisGrammar.initialize()

def unload():
    global thisGrammar
    if thisGrammar: thisGrammar.unload()
    thisGrammar = None

if __name__ == '__main__':
    try:
        natlink.waitForSpeech()
    finally:
        natlink.natDisconnect()
```

**Comment by LexiconCode** [comment]
Out of process
```
GramClassBase.load, Error at loading the grammar: A SRERR_NOUSERSELECTED error occurred calling ISRCentral::GrammarLoad from GrammarObject.cpp 283.
Traceback (most recent call last):
  File "c:\Users\MainLaptop\Documents\Caster\_test.py", line 26, in <module>
    thisGrammar.initialize()
  File "c:\Users\MainLaptop\Documents\Caster\_test.py", line 17, in initialize
    self.setList("list", ["good", "bad"])
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 888, in setList
    self.emptyList(listName)
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python310-32\lib\site-packages\natlinkcore\natlinkutils.py", line 874, in emptyList
    raise ValueError( 'list "%s" was not defined in the grammar, validLists: %s' % (listName, self.validLists))
ValueError: list "list" was not defined in the grammar, validLists: []
```

**Comment by Danesprite** [comment]
Sorry for the late reply, @LexiconCode.

I'm not sure why it is printed out twice, but yes, that is a reasonable outcome for *natspeak.exe*.

The other error you're seeing is likely unrelated.  `SRERR_NOUSERSELECTED` indicates the user profile has not yet been loaded.  It looks like this error is handled improperly in *natlinkutls.py*.  Consequently, when `setList()` is called, another error occurs.

I do not see the point of using Natlink in this fashion.  If the library is to be used "out of process," DNS should have started up properly and the Natlink messages window should be present.  There should be no need to close DNS as long as each grammar is unloaded before the remote process -- *python.exe* -- disconnects.  And that might be done automatically anyway, I don't recall.

Incidentally, I have run Dragonfly's test suite for years now without having to close/restart DNS.

**Comment by Danesprite** [comment]
@quintijn

There are a number of Natlink quirks like this one that are likely unfixable.  It might be better to simply list them all together in one place and reserve the GitHub issue tracker for things that can be fixed.  What I have in mind is something like the sections sometimes found at the end of UNIX manual pages, e.g. [csh(1), *Bugs*](https://man.openbsd.org/csh#BUGS).

Do you know if there is a sort of Natlink "bugs," "caveats," or "limitations" list somewhere already?

**Comment by quintijn** [comment]
Hi Dane, I had read this one before, but it was not in my attention. I will look at this soon (still on vacation for the coming week).

Please mention other things as an issue too, More structure we can think about later, first see what we can tackle...

**Comment by Danesprite** [comment]
Hi Quintijn,

No problem, this is not a pressing issue.  Hope you enjoy your vacation.

I'll put a list of things together soon and open a new issue.

**Comment by dougransom** [comment]
hi Dane, I added you as a potential assignee as well. If anyone wants to take a stab at this they would be welcome.

**Comment by quintijn** [comment]
I will take the first step on this!

**Comment by Danesprite** [comment]
Thank you, Doug.  I did investigate this, but got no further than tracing the code path of `GramObj.appendList()' to the COM methods in speech.h.

The odd thing is that no error is reported.  That is, there is no indication from DNS that list operations fail.  (A NatError would be raised in that case.)  Since lists do work "in process," this makes me think it's an obscure bug on the DNS side.

Again, this issue is not pressing.  I would be content to have it documented somewhere.

**Comment by quintijn** [comment]
Dane, when trying your grammar, it just works. Recently there was a fix with recognitionMimic and lists. Could you please try again your example grammar, after installing the latest installer, that LexiconCode will release soon?

**Comment by Danesprite** [comment]
All right.  I think this issue can be closed then.

**Comment by drmfinlay** [comment]
This is still an issue with Dragon 15.  It only occurs out of process.  I'm reopening this issue because of #198.

Strangely, I can add and speak list items if they're single characters — letters and numbers.  It seems that any item longer than one character will append to a list successfully, but won't match via speech or mimic.
